### ISSUE TITLE
Spring Boot Docker 部署 使用内联的方式连接Docker部署的MySQL

### ISSUE THREAD

**Issue by xiaozefeng** [xiaozefeng/docker-guide#2]

**Comment by xiaozefeng** [comment]
简单描述一下需求
有一个spring boot 的应用，使用Docker去部署，然后这个应用需要连接mysql, 而这个msyql 实例也是通过docker 部署的。
那么如果在 spring boot 中配置连接到mysql?

**Comment by xiaozefeng** [comment]
第一种方式
可以通过启动mysql时，暴露端口给宿主机
spring boot 应用配置时，使用宿主机ip+mysql暴露的端口
优点是简单直接，容易理解

**Comment by xiaozefeng** [comment]
第二种方式
容器内联，docker 提供了一种机制， 可以让容器之间直接访问，而不是通过 上面第一种方式去访问容器
具体的做法:

### 启动mysql容器
```bash
# 启动一个mysql 容器，并且指定容器名 
# root 密码为123456
docker run -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=123456 mysql
```
### spring boot 项目配置数据库
```yml
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/dms?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
```

### 编写 spring boot 项目 Docker 项目的Dockerfile
```bash
# 创建Dockerfile
touch Dockerfile
```
```dockerfile
FROM java:8

COPY *.jar /app.jar

RUN echo "Asia/shanghai" > /etc/timezone

# 这里的 --spring.profiles.active=test 参数中的test　可以修改为其他，如 dev 或 prod
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar", "--spring.profiles.active=test"]
```

### 生成镜像
1. 需要编译项目，并拿到 target目录下生产的 jar包
2. 将jar包拷贝到 Dockerfile 所在目录
3. 执行  `docker build -t spring-boot-app . `  这里的 spring-boot-app 是镜像名称, 最后的 `.` 不能省略，否则回报错

### 启动容器 (最关键的时候)
```bash
# --name spring-boo-app 指定容器名称为 spring-boot-app
# --link docker_mysql:mysql 指定docker_mysql (就是我们在上面启动的mysql容器的名称) `:mysql` 中的mysql是 docker_mysql 的别称,  这里的mysql 也是在 spring-boot 项目中数据库配置的 mysql 地址, 相当于hostname, --link 指定后　当前的容器和 docker_mysql 的网络就是想通的了，可以进入当前容器 
使用ping mysql 看看是不是通的
# 最后的spring-boot-app 是镜像名称
# 你会发现这里容器名和镜像名是一样的，你可以不用这么做
docker run -d --name spring-boot-app  -p 80:80 --link docker_mysql:mysql  spring-boot-app
